package cn.workcenter.common.constant;

import cn.workcenter.common.util.StringUtil;

public interface WebConstant extends Constant{
	
	String COLON = ":";
	String SUCCESS = "SUCCESS";
	String FAILURE = "FAILURE";
	
	int OK_STATUS = 1;
	int NO_STATUS = 0;
	
	Long WORKCENTER_ROLE_ID = 2L;
	Long KPI_ROLE_ID = 3L;
	
	Long DEVELOP_DEPART_GROUP_ID = 2L;
	
	String DEFAULT_PASSWORD = StringUtil.MD5("111111");
	
	//----WorkcenterCodeEnum 
	
	String NO_INVALID_SID = "NO_INVALID_SID";
	String NO_RUNTIMEEXCEPTION = "NO_RUNTIMEEXCEPTION";
	String NO_WRONGPASSWORD = "NO_WRONGPASSWORD";
	String NO_EXISTUSER = "NO_EXISTUSER";
	String NO_USER_ADD = "NO_USER_ADD";
	String NO_USER_UPDATE = "NO_USER_UPDATE";
	String NO_USER_DELETE = "NO_USER_DELETE";
	String NO_USER_GET = "NO_USER_GET";
	String NO_USER_FORBIDDEN = "NO_USER_FORBIDDEN";
	String NO_ROLE_ADD = "NO_ROLE_ADD";
	String NO_ROLE_GET = "NO_ROLE_GET";
	String NO_ROLE_UPDATE = "NO_ROLE_UPDATE";
	String NO_ROLE_FORBIDDEN = "NO_ROLE_FORBIDDEN";
	String NO_ROLE_DELETE = "NO_ROLE_DELETE";
	String NO_RESOURCE_ADD = "NO_RESOURCE_ADD";
	String NO_RESOURCE_GET = "NO_RESOURCE_GET";
	String NO_RESOURCE_UPDATE = "NO_RESOURCE_UPDATE";
	String NO_RESOURCE_FORBIDDEN = "NO_RESOURCE_FORBIDDEN";
	String NO_RESOURCE_DELETE = "NO_RESOURCE_DELETE";
	String NO_GROUP_ADD = "NO_GROUP_ADD";
	String NO_GROUP_GET = "NO_GROUP_GET";
	String NO_GROUP_UPDATE = "NO_GROUP_UPDATE";
	String NO_GROUP_FORBIDDEN = "NO_GROUP_FORBIDDEN";
	String NO_GROUP_DELETE = "NO_GROUP_DELETE";
	String NO_OLDPASSWORD_WRONG = "NO_OLDPASSWORD_WRONG";
	String NO_CHANGE_PASSWORD = "NO_CHANGE_PASSWORD";
	String NO_FVI_ADD = "NO_FVI_ADD";
	String NO_FVI_UPDATE = "NO_FVI_UPDATE";
	String NO_FVI_DELETE = "NO_FVI_DELETE";
	String NO_FVI_GET = "NO_FVI_GET";
	String NO_FVI_FORBIDDEN = "NO_FVI_FORBIDDEN";
	String NO_FVA_ADD = "NO_FVA_ADD";
	String NO_FVA_UPDATE = "NO_FVA_UPDATE";
	String NO_FVA_DELETE = "NO_FVA_DELETE";
	String NO_FVA_GET = "NO_FVA_GET";
	String NO_FVA_FORBIDDEN = "NO_FVA_FORBIDDEN";
	
	String OK_SUCCESS = "OK_SUCCESS";
	String OK_LOGOUT = "OK_LOGOUT";
	String OK_LOGIN = "OK_LOGIN";
	String OK_USER_ADD = "OK_USER_ADD";
	String OK_USER_UPDATE = "OK_USER_UPDATE";
	String OK_USER_DELETE = "OK_USER_DELETE";
	String OK_USER_GET = "OK_USER_GET";
	String OK_USER_FORBIDDEN = "OK_USER_FORBIDDEN";
	String OK_ROLE_ADD = "OK_ROLE_ADD";
	String OK_ROLE_GET = "OK_ROLE_GET";
	String OK_ROLE_UPDATE = "OK_ROLE_UPDATE";
	String OK_ROLE_FORBIDDEN = "OK_ROLE_FORBIDDEN";
	String OK_ROLE_DELETE = "OK_ROLE_DELETE";
	String OK_RESOURCE_ADD = "OK_RESOURCE_ADD";
	String OK_RESOURCE_GET = "OK_RESOURCE_GET";
	String OK_RESOURCE_UPDATE = "OK_RESOURCE_UPDATE";
	String OK_RESOURCE_FORBIDDEN = "OK_RESOURCE_FORBIDDEN";
	String OK_RESOURCE_DELETE = "OK_RESOURCE_DELETE";
	String OK_GROUP_ADD = "OK_GROUP_ADD";
	String OK_GROUP_GET = "OK_GROUP_GET";
	String OK_GROUP_UPDATE = "OK_GROUP_UPDATE";
	String OK_GROUP_FORBIDDEN = "OK_GROUP_FORBIDDEN";
	String OK_GROUP_DELETE = "OK_GROUP_DELETE";
	String OK_CHANGE_PASSWORD = "OK_CHANGE_PASSWORD";
	String OK_FVI_ADD = "OK_FVI_ADD";
	String OK_FVI_UPDATE = "OK_FVI_UPDATE";
	String OK_FVI_DELETE = "OK_FVI_DELETE";
	String OK_FVI_GET = "OK_FVI_GET";
	String OK_FVI_FORBIDDEN = "OK_FVI_FORBIDDEN";
	String OK_FVA_ADD = "OK_FVA_ADD";
	String OK_FVA_UPDATE = "OK_FVA_UPDATE";
	String OK_FVA_DELETE = "OK_FVA_DELETE";
	String OK_FVA_GET = "OK_FVA_GET";
	String OK_FVA_FORBIDDEN = "OK_FVA_FORBIDDEN";
	String OK_USERROLE_UPDATE = "OK_USERROLE_UPDATE";
	String OK_USERGROUP_UPDATE = "OK_USERGROUP_UPDATE";
	String OK_ROLERESOURCE_UPDATE = "OK_ROLERESOURCE_UPDATE";
	
	//----WorkcenterOperationEnum englishname
	String LOGIN = "LOGIN";
	String LOGOUT = "LOGOUT";
	String CHANGE_PASSWORD = "CHANGE_PASSWORD";
	//user model
	String USER_ADD = "USER_ADD";
	String USER_GET = "USER_GET";
	String USER_EDIT = "USER_EDIT";
	String USER_FORBIDDEN = "USER_FORBIDDEN";
	String USER_DELETE = "USER_DELETE";
	
	//role model
	String ROLE_ADD = "ROLE_ADD";
	String ROLE_GET = "ROLE_GET";
	String ROLE_EDIT = "ROLE_EDIT";
	String ROLE_FORBIDDEN = "ROLE_FORBIDDEN";
	String ROLE_DELETE = "ROLE_DELETE";
	
	//resource model
	String RESOURCE_ADD = "RESOURCE_ADD";
	String RESOURCE_GET = "RESOURCE_GET";
	String RESOURCE_EDIT = "RESOURCE_EDIT";
	String RESOURCE_FORBIDDEN = "RESOURCE_FORBIDDEN";
	String RESOURCE_DELETE = "RESOURCE_DELETE";
	
	//group model
	String GROUP_ADD = "GROUP_ADD";
	String GROUP_GET = "GROUP_GET";
	String GROUP_EDIT = "GROUP_EDIT";
	String GROUP_FORBIDDEN = "GROUP_FORBIDDEN";
	String GROUP_DELETE = "GROUP_DELETE";
	//FlowVariableinstance
	String FVI_ADD = "FVI_ADD";
	String FVI_GET = "FVI_GET";
	String FVI_EDIT = "FVI_EDIT";
	String FVI_FORBIDDEN = "FVI_FORBIDDEN";
	String FVI_DELETE = "FVI_DELETE";
	
	//FlowVariableAccess
	String FVA_ADD = "FVA_ADD";
	String FVA_GET = "FVA_GET";
	String FVA_EDIT = "FVA_EDIT";
	String FVA_FORBIDDEN = "FVA_FORBIDDEN";
	String FVA_DELETE = "FVA_DELETE";
	
	//user role
	String USER_UPDATEROLE = "USER_UPDATEROLE";
	String USER_UPDATEGROUP = "USER_UPDATEGROUP";
	String ROLE_UPDATERESOURCE = "ROLE_UPDATERESOURCE";
}
